### ISSUE TITLE
- Scene System

### ISSUE THREAD

**Issue by odecay** [fishfight/punchy#13]
The first iteration of a scene system requires a way to define and load levels from a file.

This will require some sort of prefab for spawning in different types of enemy.

**Comment by zicklag** [comment]
This is something I've done a little bit of work with in Bevy.

What kind of format do you think we want to use for prefabs and levels?

I tend to lean away from JSON for anything that we expect humans to write. It's quite annoying to hand-type with the rules such as no-trailing commas, and all of the extra quotes around keys.

RON seems popular in the Rust ecosystem, but I still seem to prefer YAML over RON when humans are typing it because it's easier to type out, more common as far as editor support and general ecosystem is concerned.

The biggest reason I switch to using RON for anything in a given scenario is when I need to store a HashMap that has keys that are non-strings. RON is the only format out of it, YAML, and JSON that supports non-string keys with Serde out-of-the-box.

So I would recommend YAML or RON, but YAML is my slightly preferred option.

Also, it's easy to switch later, and a conversion from one format to another can be fully automated with a simple Rust script, so it's not a big deal if we want to try one and see how it feels first.

**Comment by zicklag** [comment]
Yeah, this is similar to what I need to do for my own game right now, so I figure I'll help you out while getting free code review for code that's going to be put into my game in a similar way. :smile: 

I think enemies will look something like this in YAML:

```yaml
name: Sharky
kind: enemy
spritesheet:
  image: ../sprites/sharky.png

  animation_fps: 0.12
  animations:
    idle: [0, 3]
    running: [8, 11]
    knocked_right: [40, 46]
    knocked_left: [40, 46]
    dying: [71, 76]
    attacking: [85, 90]
```

I've already gotten parallax backgrounds loading from an asset.

I'm going to try strategy of having:

- A main game metadata YAML that lists the levels and the sets the player, until we have UI, a default level that will start immediately
- Level YAML files that will have the parallax background info, and the list of enemies and where they spawn
- Fighter YAML files such as "Sharky" above, that will define all of the stats for the fighters

It shouldn't take too long to set up and get a feel for whether it works well.
